### ISSUE TITLE
[Request] Adding this app to F-Droid

### ISSUE THREAD

**Issue by ShapeShifter499** [limboemu/limbo#1]
Hi

I just tested this on a Marshmallow based Cyanogenmod 13 rom and it works better then expected. I was a bit worried about installing apk since the original Limbo PC emulator project was abandoned. Since this is appears to be open source is there a chance this app could be added to the Open Source F-Droid market? Would make it more friendly for potential people to use.

**Comment by limboemu** [comment]
Hi ShapeShifter, the only thing keeping this from f-droid is their automatic build process which I can tell needs to be supported by Limbo custom build environment. Currently there is a manual configuration process involved (see [https://github.com/limboemu/limbo/blob/master/README]) with non-standard NDK commands which complicates things. Hopefully me or someone will contribute a way to make it more f-droid friendly in the future.

**Comment by ShapeShifter499** [comment]
I see, I don't know programming too terribly yet so I probably can't help at this point but I hope someone does.  

By the way, thank you for upgrading this to work with newer Android builds.
