### ISSUE TITLE
Add "Expert" option

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#14]
Let users specify parameters manually (as is in cmd)

**Comment by limboemu** [comment]
Specifying additional parameters is a good idea that won't take long time. This will be scheduled in the next release.

**Comment by limboemu** [comment]
I closed the other tickets for expert options since you may specify any advanced option. Please do not open any other advanced settings unless they are updates to already provided option on the UI.

**Comment by MVoloshin** [comment]
OK

**Comment by limboemu** [comment]
added in 0fb9a6c
