### ISSUE TITLE
Port QEMU-ARM and MIPS for Android

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#17]

**Comment by MagicInventor** [comment]
and powerpc

**Comment by limboemu** [comment]
Will review after Summer Vacation.

**Comment by armleo** [comment]
What problems exist with qemu arm porting? What about vitualiztion of arm on arm?

**Comment by limboemu** [comment]
ARM/64 and PowerPC emulators are enabled for Android for ARM and x86 archs.
ARM on ARM is enabled but it requires a KVM enabled kernel, currently not fully tested.
