### ISSUE TITLE
Add more CPU models

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#22]
Do not forget to try, if they are supported by built-in QEMU!
32-bit:
"pentiumpro"
"kvm32"
64-bit:
"qemu64"
"Conroe"
"Penryn"
"Westmere"
"SandyBridge"
"Haswell"
"Opteron_G1"
"Opteron_G2"
"Opteron_G3"
"Opteron_G4"
"Opteron_G5"

**Comment by limboemu** [comment]
Low priority.

**Comment by limboemu** [comment]
Will add Nehalem here.

**Comment by limboemu** [comment]
added in b6f7592
