### ISSUE TITLE
"QEMU Monitor" displays serial0 console instead of QEMU Monitor itself

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#3]
"QEMU Monitor" displays serial0 console instead of QEMU Monitor itself

**Comment by limboemu** [comment]
Fixed in 1584706.

Monitor Virtual Console and QMP Server seem to be working exclusively to each other.
Enabled monitor Virtual Console only for VNC
SDL for Android doesn't support multiple windows so we enable QMP server for saving state.
