### ISSUE TITLE
-enable-kvm is not working in Limbo

### ISSUE THREAD

**Issue by AndrewAVX** [limboemu/limbo#30]
I installed your snapshot of Limbo with KVM support on my device (Zenfone 2 ZE551ML) and Limbo is not running VM with "Enable KVM", but it running VM without "Enable KVM".
I don't know why is this error. You can watch the video (https://www.youtube.com/watch?v=5iDLZ87yitU) and find out why is this error.

**Comment by MVoloshin** [comment]
I think you should also provide adb logcat output.

**Comment by AndrewAVX** [comment]
adb logcat output: [logcat.txt](https://github.com/limboemu/limbo/files/381041/logcat.txt)

**Comment by limboemu** [comment]
Please do not create new issues, there is already #11 
Will continue discussion there.
