### ISSUE TITLE
Kvm is not working on armv7

### ISSUE THREAD

**Issue by yunus70** [limboemu/limbo#33]

**Comment by yunus70** [comment]
when I press the button kvm then closes the app

**Comment by MVoloshin** [comment]
KVM is a virtualization technology. Limbo emulates x86 PC. Then, if you want using KVM, you need host with same arch and KVM modules built into the kernel.

**Comment by yunus70** [comment]
how does it work

**Comment by limboemu** [comment]
Please read more about [KVM](https://www.linux-kvm.org/page/Main_Page)
