### ISSUE TITLE
Limbo emulator is to slow

### ISSUE THREAD

**Issue by yunus70** [limboemu/limbo#34]
I have on windows xp 100% cpu usage

**Comment by HuangLuxuan** [comment]
the cpu usage is always wrong in emulator

**Comment by yunus70** [comment]
why that's wrong

**Comment by yunus70** [comment]
I have the bochs pc emulator tested , it was 3 times faster than limbo pc emulator .My Cpu usage was 60-80 %

**Comment by MVoloshin** [comment]
Compare performance of your PC with Android phone and you will understand, why.

**Comment by yunus70** [comment]
which is a pc with a right proccesor , would the limbo emulator a root access then he would work on my proccessor

**Comment by limboemu** [comment]
Unfortunately Limbo is not meant to be used for large OSes, you may try enabling KVM.
