### ISSUE TITLE
Unneeded CPU model

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#45]
I think "Default" model choice is a duplicate of some another model.

**Comment by evg-zhabotinsky** [comment]
Not really a problem, although putting `(default)` after real arch name instead would be better.

**Comment by limboemu** [comment]
At this point Default is not passing a cpu argument to QEMU at all. Internally though QEMU is pointing to qemu32 or qemu64. This might change in the future so it's good not to make any assumptions at this point and leaving it as is.
