### ISSUE TITLE
QEMU 2.7

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#46]
2.3 is very outdated. Then, in 2.7, there are a lot of TCG optimizations, giving +20% speed.

**Comment by yunus70** [comment]
where is the download link

**Comment by limboemu** [comment]
After my preliminary testing it doesn't seem it has a tremendous effect on speed on ARM hosts. Perhaps the performance was tested on x86.

**Comment by MVoloshin** [comment]
I think you should update built-in QEMU anyway.

**Comment by MVoloshin** [comment]
Ready...
