### ISSUE TITLE
[Request] Combine this project with one on SourceForge

### ISSUE THREAD

**Issue by vynncentgm** [limboemu/limbo#48]
As the maintainer of Limbo PC Emulator on SF (sourceforge.net/projects/limbopcemulator/), I feel that adding your apks and source (with credit of course!) to mine would be beneficial to everybody as I have 4000+ downloads per week. And that is just the original code and app as it had appeared in 2014-2016.

I'm sure that many who come to my project haven't heard of yours, and would willing to try it.
For now, I'll host your apks, if you don't want me to do that, I will take them down. 

Vynncent

**Comment by yunus70** [comment]
Bad idea

**Comment by ShapeShifter499** [comment]
@vynncentgm @limboemu  Might be a good idea, but I'd also love to see LimboPC go to F-Droid, as I mentioned in #1, and maybe even Google Play

**Comment by yunus70** [comment]
Bad idea

**Comment by ShapeShifter499** [comment]
@yunus70 Why is this a bad idea?

**Comment by evg-zhabotinsky** [comment]
I'd suggest also putting links to *this* repo and http://limboemulator.weebly.com/ on SF.
For a while I wondered, how the hell SF has fresh binaries but GitHub repo it points to is dead?
I found this repo only 5 minutes ago by by accidentally clicking a link inside Limbo itself.

**Comment by vynncentgm** [comment]
@evg-zhabotinsky I already have (in a readme file). I haven't added it to the 2.4.0 directory yet, but it is in the 2.2.3 directory.

https://sourceforge.net/projects/limbopcemulator/files/Current%20Releases/Ver%202.2.3%20%5BUNOFFICIAL%5D%20%5BStable%5D/

**Comment by limboemu** [comment]
This is Open Source Software you are allowed to modify code and redistribute binaries and code without explicit permission in accordance with the [license](https://github.com/limboemu/limbo/blob/master/COPYING). Everything else is your choice.
