### ISSUE TITLE
Force landscape orientation on devices with low screen resolutions

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#5]
On my Philips Xenium W3568 (800x480) (portrait mode) some text is hidden or does not fit on the screen in Limbo main menu. In both VNC and SDL interfaces text is too small and unreadable in text-mode OSes. Then it is hard to move the mouse cursor in GUI-based OSes. I do not want to use Auto-rotate, because it is uncomfortably.

**Comment by limboemu** [comment]
Added Orientation option in 4f5b031.
