### ISSUE TITLE
How add 2 or 3 network card in limbo??

### ISSUE THREAD

**Issue by arashazad5** [limboemu/limbo#59]
Limbo in run perfectly but just add one network card please help me to add two or more network card (my tablet support lan configuration )
Do add micro usb lan into limbo?

**Comment by yunus70** [comment]
Nice tablet

**Comment by arashazad5** [comment]
Please help me

**Comment by yunus70** [comment]
I can't help

**Comment by limboemu** [comment]
Unfortunately the Limbo UI doesn't allow for multiple network interfaces. Though you can try adding the network interface via the Extra QEMU Params (Bottom of the screen). For more information see [QEMU Networking](https://en.wikibooks.org/wiki/QEMU/Networking)
