### ISSUE TITLE
File manager

### ISSUE THREAD

**Issue by Quang-vip** [limboemu/limbo#60]
Please use the limbo's file manager, not the system's default file manager (I'm having a problem with it)

**Comment by vishalaj** [comment]
How will the file manager come?My phone file is not showing in Windows.please help

**Comment by Quang-vip** [comment]
What do you mean?

**Comment by DEMON74066** [comment]
Is there a way I can move files from my phone to the emulated PC?

**Comment by Quang-vip** [comment]
Use vfat method

**Comment by DEMON74066** [comment]
OK thank you

**Comment by limboemu** [comment]
Limbo 4.0.0 provides a method to open files via the legacy file manager.
