### ISSUE TITLE
The no bootable device

### ISSUE THREAD

**Issue by thuanduc1905** [limboemu/limbo#65]
# Why this?`siht yhW¿`

**Comment by shivakugwe** [comment]
No bootable device

**Comment by shivakugwe** [comment]
What we do

**Comment by Quang-vip** [comment]
Ah

**Comment by kokoironman** [comment]
i also no bootable device. why?

**Comment by kokoironman** [comment]
how to download xp.img file

**Comment by fscone1** [comment]
Hello

**Comment by Quang-vip** [comment]
...

**Comment by kokoironman** [comment]
I want download XP.img file. please link

**Comment by Quang-vip** [comment]
Just SEARCH it on Google

**Comment by Quang-vip** [comment]
Or...

**Comment by Quang-vip** [comment]
https://drive.google.com/file/d/0BySnPp1qOihVc01tN1N1cG5IV28/view?usp=drivesdk

Extract it

**Comment by kokoironman** [comment]
already download xp.img file. but no help file.

**Comment by kokoironman** [comment]
not see xp.img file

**Comment by Quang-vip** [comment]
WHAT?

**Comment by Quang-vip** [comment]
WHATTTTTTT????????????????__???__

**Comment by kokoironman** [comment]
i download xp.img file. but can not find xp.img file.

**Comment by Quang-vip** [comment]
You ***** and d*g *****

**Comment by Quang-vip** [comment]
GET IN DOWNLOADS FOLDER

**Comment by kokoironman** [comment]
i want my android in xp style. ok,thank you.

**Comment by Quang-vip** [comment]
FUC;-(]_!)@_](]_

**Comment by fscone1** [comment]
Wtf

**Comment by sbdeveloper1** [comment]
When you finished to download OS image put it as CD-ROM and put boot as CD-ROM option.
