### ISSUE TITLE
how to build qemu on windows

### ISSUE THREAD

**Issue by HuangLuxuan** [limboemu/limbo#67]
is there any one can tell me how to build qemu on windows? i have tried Makefile in jni folder and it told me no rule to make qemu.mak. i tried cygwin too,but it doesn't work either. it told me to run configure first but configure told me 'cc either  does not exist or does not work'. does anyone can help me. and cc does work!!

**Comment by limboemu** [comment]
Compiling on Windows is not supported with recent versions. You can try creating an ubuntu virtual machine using VirtualBox and compile limbo.

**Comment by UnMe0w** [comment]
or use wsl if you are on Windows 10
