### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by NeverMine17** [limboemu/limbo#68]
Ubuntu 16.04 LTS "Xenial Xerus" Minimal CD.
Keyboard not working in boot menu.

**Comment by Auxilus** [comment]
Yeah whenever I try to install Ubuntu it fails it shows complete black screen as soon as I hit install..

**Comment by Auxilus** [comment]
BTW I am using OnePlus 2 , so can you fix it ?

**Comment by limboemu** [comment]
Unfortunately Ubuntu is not supported, you should try Hacker's Keyboard you can find it in Google Play store.
