### ISSUE TITLE
My Computer fails in Windows 95

### ISSUE THREAD

**Issue by Auxilus** [limboemu/limbo#69]
I ran windows 95 with shared folder and opened my computer , but it crashed .... Any way to access phone files in VM ?

**Comment by 03453741955** [comment]
03453741955

**Comment by limboemu** [comment]
Unfortunately Windows 95 is not supported. Although not recommended you can try the vfat disks via Shared Folder to share files with android.

**Comment by limboemu** [comment]
Unfortunately Windows 95 is not supported. Although not recommended you can try an ftp server inside your VM to share files with android. You will need to setup an Network connection to do this.
