### ISSUE TITLE
Add 4 MB memory option

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#7]
4 MB is enough for some systems too.

**Comment by limboemu** [comment]
Added in 7786a46

**Comment by biz4race** [comment]
This app has stopped on Samsung note 4, with set cpu:1 and ram:456 or more!!!
Why this happened?
Samsung note 4 has enough ability to run it!
Also there is not any option for more ram, more than 1g...

**Comment by yunus70** [comment]
Add 4 mb memory option are you fuucking idiot it will not work no system will work with 4 mb  minimum 128
