### ISSUE TITLE
I can't run Windows xp

### ISSUE THREAD

**Issue by Auxilus** [limboemu/limbo#70]
I can't run Windows XP in qemu...it says no bootable device found and some other errors

**Comment by alio1300A** [comment]
What device are you using and what version of android. XP installed and boots fine on my S7, (Admittedly I had to update and change to sdl mode) BE PREPARED FOR 3 HOURS UPWARDS FOR INSTALL AND THEN 5 MINUTES TO BOOT EVERYTIME. Also, your iso might just be bad.

**Comment by limboemu** [comment]
Unfortunately Windows XP is not supported.
