### ISSUE TITLE
shutdown linux virtual systems and  completely quit the app

### ISSUE THREAD

**Issue by jingwen369** [limboemu/limbo#88]
I created a number of linux virtual systems, I started one of the systems, then shut down the system, shut down the system and completely quit the app, should return to the main interface

**Comment by limboemu** [comment]
Unfortunately, since there is a problem with reloading the native libraries the only way to do shutoff the virtual machine is to hard exit from the jvm that means that the whole app will exit.

**Comment by jingwen369** [comment]
You can modify the native library so file to resolve this issue？

**Comment by jingwen369** [comment]
You can modify the libSDL2.so file to resolve this issue
