### ISSUE TITLE
Persistent Internet Connection Attempts to "raw.githubusercontent.com" ?

### ISSUE THREAD

**Issue by phuyuk** [limboemu/limbo#89]
I just noticed that Limbo x86 is making connection attempts to "raw.githubusercontent.com", apparently every time the app starts up. It's a bit worrisome. Why is it happening?

**Comment by limboemu** [comment]
The app is simply checking for a new version in the repo (github) on startup, see [Config.java](https://github.com/limboemu/limbo/blob/master/limbo-android-lib/src/main/java/com/max2idea/android/limbo/main/Config.java) String constant defines the full URL:  
 **public static final String downloadUpdateLink = "https://raw.githubusercontent.com/limboemu/limbo/master/VERSION";**

**Comment by phuyuk** [comment]
Thank you very much for addressing this.

As an F-Droid consumer, I have three concerns:

1)  The application makes silent, unannounced, unexpected network connections, no matter the intentions.
2)  The network connections are unrelated to the app's core function - emulation.
3)   Automatic updates - or even checking for updates - outside of F-Droid, may run counter to a user's desires.

A healthy subset of F-Droid users are very sensitive to both privacy and security; rightly or wrongly, many believe that these risks are mitigated by exercising self-restraint, and installing apps only from F-Droid.   With that in mind, background connections to another repo fundamentally undermines their intentions.

Please consider disabling this activity in the F-Droid build - or at least present an option to permanently disable it.

Thank you for an oustanding app, by the way. I'm really enjoying it!

**Comment by limboemu** [comment]
Hi, the connection for version updates are made to this same repo. Also, links to the binaries can be found in the [wiki ](https://github.com/limboemu/limbo/wiki/Downloads) of this same repo. 

As far as F-Droid goes I'm not maintaining the distribution in F-Droid, you might want to check with the distributor instead to remove these checks in their fork.

**Comment by limboemu** [comment]
There is already a "Don't Show Again" check box in the dialog box but that's only when a new version is found. What I can do is add a similar option in the settings.

Keep in mind, open source software by nature may have different forks and multiple distribution points like Android store or F-Droid depending on additional features they provide. As far as this repo goes you will find new binaries in links indicated only in this repo's home page: https://github.com/limboemu/limbo as always.

**Comment by phuyuk** [comment]
Thank you for the explanation. It didn't occur to me that the F-Droid build is a fork. I'm sorry about that. As for the background update checks, I became aware of them only after browsing through my firewall logs. It's the network connection, itself, that disturbs me - not 'update available' messages. IMHO, the option should disable automatic update checks, rather than just suppressing messages.

No matter, I believe you, that the connection has no ulterior/commercial/nefarious purpose.

Until this rightfully gets sorted out on F-Droid, my firewall and Adaway are blocking the app and domain... just for [my neurotic] good measure.

Thanks again - the app is lovely.

**Comment by limboemu** [comment]
Added in v4.1.0
