### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by WASasquatch** [limboemu/limbo#91]
I am not able to install Limbo x86 PC Emulator for ARM devices on my LG G8 ThinQ. It simply says: App Not Installed. 

3.0 worked fine. 

![Screenshot_20190530-192531](https://user-images.githubusercontent.com/1151589/58677420-b6bbff00-8310-11e9-8957-b38957f643c3.png)

**Comment by WASasquatch** [comment]
Figured it out. The 3.x version was only disabled and Android attempts to update the original disabled version, which it is unable to do. 

Make sure 2.x/3.x versions are fully uninstalled before installing 4.x.

**Comment by limboemu** [comment]
Thanks for the fix, I've added a note in the wiki download page.
