### ISSUE TITLE
What happened to the official website to download the iso?

### ISSUE THREAD

**Issue by lollipoppermodpes** [limboemu/limbo#94]
What happened to the official website to download the iso?

**Comment by limboemu** [comment]
Hi, most of the content is now moved to github, the wiki is where you can find the guides and links to ISOs and images for supported OSes. I have also updated the link to download the DSL Linux ISO from the respective wiki [page](https://github.com/limboemu/limbo/wiki/DSL-linux).
https://github.com/limboemu/limbo/wiki
